### ISSUE TITLE
Errors connecting to AppWrite in Next.js 14

### ISSUE THREAD

**Issue by kkatusic** [hiteshchoudhary/nextjs-appwrite-auth#3]
I used this code inside Next.js 14 and it doesn't work. Getting error:

![Screenshot 2024-01-19 at 15 32 54](https://github.com/hiteshchoudhary/nextjs-appwrite-auth/assets/1242145/4183dcf4-7c9a-4c1b-82e0-c0995f23b135)

as I can research it has problem with using this appwrite/config.ts class inside component some cookie related issue :(

If someone figure out how it can be fix please reply here.

**Comment by felix-d1strict** [comment]
Hello,

that's not really a error. You must be logged in, then no error will be thrown.

The error is generated in this case because it queries whether the current user has an account - which throws an error in this case, as the user is not logged in.

The solution would be to catch this specific error.

**Comment by kkatusic** [comment]
> Hello,
> 
> that's not really a error. You must be logged in, then no error will be thrown.
> 
> The error is generated in this case because it queries whether the current user has an account - which throws an error in this case, as the user is not logged in.
> 
> The solution would be to catch this specific error.

Than excellent, thank you @felix-d1strict
